(()=>{'use strict';
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches;
const scenes=[{base:'assets/fracture.webp',reveal:'assets/terrain.webp'},{base:'assets/terrain.webp',reveal:'assets/monolith.webp'},{base:'assets/monolith.webp',reveal:'assets/fracture.webp'}];
const stage=$('.stage'),base=$('#sceneBase'),reveal=$('#sceneReveal'),lens=$('#heroLens'),controls=$$('.scene-switch');
let sceneIndex=0,px=.7,py=.48,inside=false,raf=0;
function updateScene(i){sceneIndex=(i+scenes.length)%scenes.length;base.style.backgroundImage=`url('${scenes[sceneIndex].base}')`;reveal.style.backgroundImage=`url('${scenes[sceneIndex].reveal}')`;controls.forEach((b,n)=>{const is=n===sceneIndex;b.classList.toggle('active',is);b.setAttribute('aria-pressed',is?'true':'false')});}
controls.forEach((b,i)=>{b.addEventListener('click',()=>updateScene(i));b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();let idx=(i+(e.key==='ArrowRight'?1:-1)+3)%3;controls[idx].focus();updateScene(idx)}})});
function frame(){raf=0;if(!inside||reduce)return;const cx=px*100,cy=py*100;reveal.style.clipPath=`circle(${Math.min(innerWidth>680?19:25,25)}% at ${cx}% ${cy}%)`;lens.style.left=cx+'%';lens.style.top=cy+'%';const dx=(px-.5)*26,dy=(py-.5)*20;base.style.transform=`translate3d(${-dx*.28}px,${-dy*.25}px,0) scale(1.06)`;reveal.style.transform=`translate3d(${-dx*.54}px,${-dy*.4}px,0) scale(1.06)`;}
function move(e){if(reduce||e.pointerType==='touch')return;const el=e.target.closest('.stage');if(!el)return;const r=stage.getBoundingClientRect();px=Math.max(0,Math.min(1,(e.clientX-r.left)/r.width));py=Math.max(0,Math.min(1,(e.clientY-r.top)/r.height));inside=true;stage.classList.add('is-pointing');if(!raf)raf=requestAnimationFrame(frame);}
stage.addEventListener('pointermove',move,{passive:true});stage.addEventListener('pointerleave',()=>{inside=false;stage.classList.remove('is-pointing');reveal.style.clipPath='circle(0 at 70% 50%)';base.style.transform='translate3d(0,0,0) scale(1.04)';reveal.style.transform='translate3d(0,0,0) scale(1.04)'});
updateScene(0);
const stages=[
 {title:'Passive collection',text:'Capture network traffic non-intrusively, reconstruct flows and extract useful features for downstream analysis.',tech:'PYTHON / SCAPY / PYSHARK'},
 {title:'Hybrid detection',text:'Explore supervised and unsupervised ML techniques for detecting anomalous activity and classifying known attack patterns.',tech:'ISOLATION FOREST / LIGHTGBM / RANDOM FOREST / XGBOOST'},
 {title:'Threat context',text:'Connect suspicious network indicators with external reputation and intelligence sources to enrich analyst context.',tech:'VIRUSTOTAL / OTX / ABUSEIPDB / SHODAN'},
 {title:'Response research',text:'Investigate policy-driven containment and correlation opportunities within the project roadmap. Not a claim of production automation.',tech:'XDR ROADMAP / POLICY RESEARCH / RESPONSE DESIGN'}
];
const tabs=$$('.step');function setStep(n){tabs.forEach((b,i)=>{b.classList.toggle('current',i===n);b.setAttribute('aria-selected',i===n?'true':'false');b.tabIndex=i===n?0:-1});$('#stepInfo').setAttribute('aria-labelledby','stepTab'+n);$('#stepId').textContent='/ 0'+(n+1);$('#stepName').textContent=stages[n].title;$('#stepDescription').textContent=stages[n].text;$('#stepTech').textContent=stages[n].tech;}
tabs.forEach((b,n)=>{b.addEventListener('click',()=>setStep(n));b.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'||e.key==='Home'||e.key==='End'){e.preventDefault();let idx=e.key==='Home'?0:e.key==='End'?tabs.length-1:(n+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;tabs[idx].focus();setStep(idx)}})});setStep(0);
const menu=$('#menuBtn'),mobile=$('#mobileNav');function close(){mobile.hidden=true;menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open navigation')};menu.addEventListener('click',()=>{const open=mobile.hidden;mobile.hidden=!open;menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close navigation':'Open navigation')});mobile.querySelectorAll('a').forEach(a=>a.addEventListener('click',close));document.addEventListener('keydown',e=>{if(e.key==='Escape')close()});
const m=$('#scrollMeter');function scroll(){const max=document.documentElement.scrollHeight-innerHeight;m.style.width=(max>0?Math.min(100,scrollY/max*100):0)+'%'}document.addEventListener('scroll',scroll,{passive:true});scroll();$('#year').textContent=new Date().getFullYear();
if('IntersectionObserver' in window&&!reduce){const io=new IntersectionObserver(entries=>{entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}})},{threshold:.1,rootMargin:'0px 0px -30px 0px'});$$('.reveal').forEach(e=>io.observe(e));const links=$$('.nav a'),active=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)links.forEach(a=>a.classList.toggle('is-active',a.getAttribute('href')==='#'+e.target.id))}),{rootMargin:'-25% 0px -66% 0px'});$$('section[id]').forEach(e=>active.observe(e));}else $$('.reveal').forEach(e=>e.classList.add('visible'));
const halo=$('#pointerHalo');if(!reduce&&matchMedia('(pointer:fine)').matches)document.addEventListener('pointermove',e=>{halo.style.transform=`translate(${e.clientX}px,${e.clientY}px) translate(-50%,-50%)`},{passive:true});else halo.style.display='none';
})();
